import "react-phone-number-input/style.css";

export const metadata = {
  title: 'Photokraft - Profile',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  )
}
