import "react-phone-number-input/style.css";

export const metadata = {
  title: "Photokrafft - Creat-Account",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <>{children}</>;
}
