export {default as OrderDetaild} from './OrderDetaild'
export {default as ProductBox} from './ProductBox'
export {default as ProductColor} from './ProductColor'
export {default as ProductOrientation} from './ProductOrientation'
export {default as ProductCover} from './ProductCover'
export {default as ProductSheet} from './ProductSheet'
export {default as ProductSize} from './ProductSize'
export {default as Product} from './Product'
