import { Poppins } from 'next/font/google'
import { Footer, Navbar } from '@/components'
import { Providers } from '@/Redux/provider'
import Script from 'next/script'
import '@/assets/css/theme.css'

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Photokraft - Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
        {/* Vendor scripts and other scripts */}
        {/* <!-- Vendor scripts: js libraries and plugins--> */}
        <Script src="./assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="./assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></Script>
        <Script src="./assets/vendor/parallax-js/dist/parallax.min.js"></Script>
        <Script src="./assets/vendor/aos/dist/aos.js"></Script>
        <Script src="./assets/vendor/@lottiefiles/lottie-player/dist/lottie-player.js"></Script>
        <Script src="./assets/vendor/img-comparison-slider/dist/index.js"></Script>
    <Script src="./assets/vendor/swiper/swiper-bundle.min.js"></Script>
        <Script src='./assets/js/theme.js' ></Script>
      </body>
    </html>
  )
}

// // 'use client'
// import { Poppins } from 'next/font/google'
// import '@/assets/css/theme.css'
// import Script from 'next/script'
// import { Footer, Navbar } from '@/components'
// import { Providers } from '@/Redux/provider'

// const poppins = Poppins({
//   weight: '400',
//   subsets: ['latin'],
//   // display: 'swap',
// })

// export const metadata = {
//   title: 'Photokraft - Home',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <>
//       <html lang='en'>
//         <body className={poppins.className} >
//           {/* <Providers> */}
//           <Providers>
//             <Navbar />
//               {children}
//             <Footer />
//           </Providers>
//           {/* </Providers> */}
         
//         </body>
//       </html>
//     </>
//   )
// }
