export {default as Footer} from './Footer'
export {default as Navbar} from './Navbar'
export {default as AnimateText} from './Sections/AnimateText'
export {default as AnimateProcessText} from './Sections/AnimateProcessText'
export {default as Testymonial} from './Sections/Testymonial'
export {default as ProductScroll} from './Sections/ProductScroll'
export {default as ProfileSectionNavbar} from './ProfileSectionNavbar'
export {default as Sidebar} from './Sidebar'

export {default as ShowProduct} from './Sections/Products/ShowProduct'
export {default as TotalCard} from './Sections/Products/TotalCard'

export {default as Checkout} from './Sections/Checkout/Checkout'
export { default as RegisterForm } from './Auth/RegisterForm'
export { default as LoginForm } from './Auth/LoginForm'
export { default as ForgetPassword } from './Auth/ForgetPassword'
export { default as NotsupportedScreen } from './NotsupportedScreen'

export { default as Profile } from './Sections/Profile/Profile'
export { default as Order } from './Sections/Profile/Order'