export const metadata = {
  title: 'Photokraft - Forget-password',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  )
}
